<?xml version="1.0" encoding="UTF-8" ?>

<!--
This file gives a list of all country subdivisions in the ISO 3166-2
standard, and is used to provide translations via gettext

The following conventions are used in this file:
If the standard lists a subdivision name in more than one language
and/or romanization system, only the first listed name is shown.

For some countries the standard also lists a second level of
regional divisions (e.g. for BE, FR, GB, IT, etc.). The codes
for these regional divisions are shown as 'XX YYYY', i.e. with a
space character instead of the '-'.

Copyright (C) 2004-2006 Alastair McKinstry <mckinstry@computer.org>
Copyright (C) 2004, 2007 Christian Perrier <bubulle@debian.org>
Copyright (C) 2005-2007 Tobias Quathamer <toddy@debian.org>
Copyright (C) 2007, 2009 LI Daobing <lidaobing@gmail.com>
Copyright (C) 2007-2010 Alexis Darrasse <alexis@ortsa.com>

    This file is free software; you can redistribute it and/or
    modify it under the terms of the GNU Lesser General Public
    License as published by the Free Software Foundation; either
    version 2.1 of the License, or (at your option) any later version.

    This file is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
    Lesser General Public License for more details.

    You should have received a copy of the GNU Lesser General Public
    License along with this file; if not, write to the Free Software
    Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA

Source: <http://www.iso.org/iso/country_codes/background_on_iso_3166/iso_3166-2.htm>
-->


<!DOCTYPE iso_3166_2_entries [
	<!ELEMENT iso_3166_2_entries (iso_3166_country+)>
  <!ELEMENT iso_3166_country (iso_3166_subset*)>
	<!ATTLIST iso_3166_country
		code			CDATA	#REQUIRED
	>
	<!ELEMENT iso_3166_subset (iso_3166_2_entry+)>
	<!ATTLIST iso_3166_subset
		type			CDATA	#REQUIRED
	>
	<!ELEMENT iso_3166_2_entry EMPTY>
	<!ATTLIST iso_3166_2_entry
		code			CDATA	#REQUIRED
		name			CDATA	#REQUIRED
		parent			CDATA	#IMPLIED
	>
]>

<iso_3166_2_entries>
	<!-- Andorra -->
<iso_3166_country code="AD">
<iso_3166_subset type="Parish">
	<iso_3166_2_entry
		code="AD-07"	name="Andorra la Vella" />
	<iso_3166_2_entry
		code="AD-02"	name="Canillo" />
	<iso_3166_2_entry
		code="AD-03"	name="Encamp" />
	<iso_3166_2_entry
		code="AD-08"	name="Escaldes-Engordany" />
	<iso_3166_2_entry
		code="AD-04"	name="La Massana" />
	<iso_3166_2_entry
		code="AD-05"	name="Ordino" />
	<iso_3166_2_entry
		code="AD-06"	name="Sant Julià de Lòria" />
</iso_3166_subset>
</iso_3166_country>
	<!-- United Arab Emirates -->
<iso_3166_country code="AE">
<iso_3166_subset type="Emirate">
	<iso_3166_2_entry
		code="AE-AZ"	name="Abū Ȥaby [Abu Dhabi]" />
	<iso_3166_2_entry
		code="AE-AJ"	name="'Ajmān" />
	<iso_3166_2_entry
		code="AE-FU"	name="Al Fujayrah" />
	<iso_3166_2_entry
		code="AE-SH"	name="Ash Shāriqah" />
	<iso_3166_2_entry
		code="AE-DU"	name="Dubayy" />
	<iso_3166_2_entry
		code="AE-RK"	name="Ra’s al Khaymah" />
	<iso_3166_2_entry
		code="AE-UQ"	name="Umm al Qaywayn" />
</iso_3166_subset>
</iso_3166_country>
	<!-- Afghanistan -->
<iso_3166_country code="AF">
<iso_3166_subset type="Province">
	<iso_3166_2_entry
		code="AF-BDS"	name="Badakhshān" />
	<iso_3166_2_entry
		code="AF-BDG"	name="Bādghīs" />
	<iso_3166_2_entry
		code="AF-BGL"	name="Baghlān" />
	<iso_3166_2_entry
		code="AF-BAL"	name="Balkh" />
	<iso_3166_2_entry
		code="AF-BAM"	name="Bāmyān" />
	<iso_3166_2_entry
		code="AF-DAY"	name="Dāykundī" />
	<iso_3166_2_entry
		code="AF-FRA"	name="Farāh" />
	<iso_3166_2_entry
		code="AF-FYB"	name="Fāryāb" />
	<iso_3166_2_entry
		code="AF-GHA"	name="Ghaznī" />
	<iso_3166_2_entry
		code="AF-GHO"	name="Ghōr" />
	<iso_3166_2_entry
		code="AF-HEL"	name="Helmand" />
	<iso_3166_2_entry
		code="AF-HER"	name="Herāt" />
	<iso_3166_2_entry
		code="AF-JOW"	name="Jowzjān" />
	<iso_3166_2_entry
		code="AF-KAB"	name="Kābul" />
	<iso_3166_2_entry
		code="AF-KAN"	name="Kandahār" />
	<iso_3166_2_entry
		code="AF-KAP"	name="Kāpīsā" />
	<iso_3166_2_entry
		code="AF-KHO"	name="Khōst" />
	<iso_3166_2_entry
		code="AF-KNR"	name="Kunar" />
	<iso_3166_2_entry
		code="AF-KDZ"	name="Kunduz" />
	<iso_3166_2_entry
		code="AF-LAG"	name="Laghmān" />
	<iso_3166_2_entry
		code="AF-LOG"	name="Lōgar" />
	<iso_3166_2_entry
		code="AF-NAN"	name="Nangarhār" />
	<iso_3166_2_entry
		code="AF-NIM"	name="Nīmrōz" />
	<iso_3166_2_entry
		code="AF-NUR"	name="Nūristān" />
	<iso_3166_2_entry
		code="AF-URU"	name="Uruzgān" />
	<iso_3166_2_entry
		code="AF-PIA"	name="Paktiyā" />
	<iso_3166_2_entry
		code="AF-PKA"	name="Paktīkā" />
	<iso_3166_2_entry
		code="AF-PAN"	name="Panjshayr" />
	<iso_3166_2_entry
		code="AF-PAR"	name="Parwān" />
	<iso_3166_2_entry
		code="AF-SAM"	name="Samangān" />
	<iso_3166_2_entry
		code="AF-SAR"	name="Sar-e Pul" />
	<iso_3166_2_entry
		code="AF-TAK"	name="Takhār" />
	<iso_3166_2_entry
		code="AF-WAR"	name="Wardak" />
	<iso_3166_2_entry
		code="AF-ZAB"	name="Zābul" />
</iso_3166_subset>
</iso_3166_country>
	<!-- Antigua and Barbuda -->
<iso_3166_country code="AG">
<iso_3166_subset type="Parish">
	<iso_3166_2_entry
		code="AG-03"	name="Saint George" />
	<iso_3166_2_entry
		code="AG-04"	name="Saint John" />
	<iso_3166_2_entry
		code="AG-05"	name="Saint Mary" />
	<iso_3166_2_entry
		code="AG-06"	name="Saint Paul" />
	<iso_3166_2_entry
		code="AG-07"	name="Saint Peter" />
	<iso_3166_2_entry
		code="AG-08"	name="Saint Philip" />
</iso_3166_subset>
<iso_3166_subset type="Dependency">
	<iso_3166_2_entry
		code="AG-10"	name="Barbuda" />
	<iso_3166_2_entry
		code="AG-11"	name="Redonda" />
</iso_3166_subset>
</iso_3166_country>
	<!-- Albania -->
<iso_3166_country code="AL">
<iso_3166_subset type="County">
	<iso_3166_2_entry
		code="AL-01"	name="Berat" />
	<iso_3166_2_entry
		code="AL-09"	name="Dibër" />
	<iso_3166_2_entry
		code="AL-02"	name="Durrës" />
	<iso_3166_2_entry
		code="AL-03"	name="Elbasan" />
	<iso_3166_2_entry
		code="AL-04"	name="Fier" />
	<iso_3166_2_entry
		code="AL-05"	name="Gjirokastër" />
	<iso_3166_2_entry
		code="AL-06"	name="Korçë" />
	<iso_3166_2_entry
		code="AL-07"	name="Kukës" />
	<iso_3166_2_entry
		code="AL-08"	name="Lezhë" />
	<iso_3166_2_entry
		code="AL-10"	name="Shkodër" />
	<iso_3166_2_entry
		code="AL-11"	name="Tiranë" />
	<iso_3166_2_entry
		code="AL-12"	name="Vlorë" />
</iso_3166_subset>
<iso_3166_subset type="District">
	<iso_3166_2_entry
		code="AL-BR"	name="Berat"	parent="01" />
	<iso_3166_2_entry
		code="AL-BU"	name="Bulqizë"	parent="09" />
	<iso_3166_2_entry
		code="AL-DL"	name="Delvinë"	parent="12" />
	<iso_3166_2_entry
		code="AL-DV"	name="Devoll"	parent="06" />
	<iso_3166_2_entry
		code="AL-DI"	name="Dibër"	parent="09" />
	<iso_3166_2_entry
		code="AL-DR"	name="Durrës"	parent="02" />
	<iso_3166_2_entry
		code="AL-EL"	name="Elbasan"	parent="03" />
	<iso_3166_2_entry
		code="AL-FR"	name="Fier"	parent="04" />
	<iso_3166_2_entry
		code="AL-GR"	name="Gramsh"	parent="03" />
	<iso_3166_2_entry
		code="AL-GJ"	name="Gjirokastër"	parent="05" />
	<iso_3166_2_entry
		code="AL-HA"	name="Has"	parent="07" />
	<iso_3166_2_entry
		code="AL-KA"	name="Kavajë"	parent="11" />
	<iso_3166_2_entry
		code="AL-ER"	name="Kolonjë"	parent="06" />
	<iso_3166_2_entry
		code="AL-KO"	name="Korçë"	parent="06" />
	<iso_3166_2_entry
		code="AL-KR"	name="Krujë"	parent="02" />
	<iso_3166_2_entry
		code="AL-KC"	name="Kuçovë"	parent="01" />
	<iso_3166_2_entry
		code="AL-KU"	name="Kukës"	parent="07" />
	<iso_3166_2_entry
		code="AL-KB"	name="Kurbin"	parent="08" />
	<iso_3166_2_entry
		code="AL-LE"	name="Lezhë"	parent="08" />
	<iso_3166_2_entry
		code="AL-LB"	name="Librazhd"	parent="03" />
	<iso_3166_2_entry
		code="AL-LU"	name="Lushnjë"	parent="04" />
	<iso_3166_2_entry
		code="AL-MM"	name="Malësi e Madhe"	parent="10" />
	<iso_3166_2_entry
		code="AL-MK"	name="Mallakastër"	parent="04" />
	<iso_3166_2_entry
		code="AL-MT"	name="Mat"	parent="09" />
	<iso_3166_2_entry
		code="AL-MR"	name="Mirditë"	parent="08" />
	<iso_3166_2_entry
		code="AL-PQ"	name="Peqin"	parent="03" />
	<iso_3166_2_entry
		code="AL-PR"	name="Përmet"	parent="05" />
	<iso_3166_2_entry
		code="AL-PG"	name="Pogradec"	parent="06" />
	<iso_3166_2_entry
		code="AL-PU"	name="Pukë"	parent="10" />
	<iso_3166_2_entry
		code="AL-SR"	name="Sarandë"	parent="12" />
	<iso_3166_2_entry
		code="AL-SK"	name="Skrapar"	parent="01" />
	<iso_3166_2_entry
		code="AL-SH"	name="Shkodër"	parent="10" />
	<iso_3166_2_entry
		code="AL-TE"	name="Tepelenë"	parent="05" />
	<iso_3166_2_entry
		code="AL-TR"	name="Tiranë"	parent="11" />
	<iso_3166_2_entry
		code="AL-TP"	name="Tropojë"	parent="07" />
	<iso_3166_2_entry
		code="AL-VL"	name="Vlorë"	parent="12" />
</iso_3166_subset>
</iso_3166_country>
	<!-- Armenia -->
<iso_3166_country code="AM">
<iso_3166_subset type="Province">
	<iso_3166_2_entry
		code="AM-ER"	name="Erevan" />
	<iso_3166_2_entry
		code="AM-AG"	name="Aragacotn" />
	<iso_3166_2_entry
		code="AM-AR"	name="Ararat" />
	<iso_3166_2_entry
		code="AM-AV"	name="Armavir" />
	<iso_3166_2_entry
		code="AM-GR"	name="Gegarkunik'" />
	<iso_3166_2_entry
		code="AM-KT"	name="Kotayk'" />
	<iso_3166_2_entry
		code="AM-LO"	name="Lory" />
	<iso_3166_2_entry
		code="AM-SH"	name="Sirak" />
	<iso_3166_2_entry
		code="AM-SU"	name="Syunik'" />
	<iso_3166_2_entry
		code="AM-TV"	name="Tavus" />
	<iso_3166_2_entry
		code="AM-VD"	name="Vayoc Jor" />
</iso_3166_subset>
</iso_3166_country>
	<!-- Angola -->
<iso_3166_country code="AO">
<iso_3166_subset type="Province">
	<iso_3166_2_entry
		code="AO-BGO"	name="Bengo" />
	<iso_3166_2_entry
		code="AO-BGU"	name="Benguela" />
	<iso_3166_2_entry
		code="AO-BIE"	name="Bié" />
	<iso_3166_2_entry
		code="AO-CAB"	name="Cabinda" />
	<iso_3166_2_entry
		code="AO-CCU"	name="Cuando-Cubango" />
	<iso_3166_2_entry
		code="AO-CNO"	name="Cuanza Norte" />
	<iso_3166_2_entry
		code="AO-CUS"	name="Cuanza Sul" />
	<iso_3166_2_entry
		code="AO-CNN"	name="Cunene" />
	<iso_3166_2_entry
		code="AO-HUA"	name="Huambo" />
	<iso_3166_2_entry
		code="AO-HUI"	name="Huíla" />
	<iso_3166_2_entry
		code="AO-LUA"	name="Luanda" />
	<iso_3166_2_entry
		code="AO-LNO"	name="Lunda Norte" />
	<iso_3166_2_entry
		code="AO-LSU"	name="Lunda Sul" />
	<iso_3166_2_entry
		code="AO-MAL"	name="Malange" />
	<iso_3166_2_entry
		code="AO-MOX"	name="Moxico" />
	<iso_3166_2_entry
		code="AO-NAM"	name="Namibe" />
	<iso_3166_2_entry
		code="AO-UIG"	name="Uíge" />
	<iso_3166_2_entry
		code="AO-ZAI"	name="Zaire" />
</iso_3166_subset>
</iso_3166_country>
	<!-- Argentina -->
<iso_3166_country code="AR">
<iso_3166_subset type="City">
	<iso_3166_2_entry
		code="AR-C"	name="Ciudad Autónoma de Buenos Aires" />
</iso_3166_subset>
<iso_3166_subset type="Province">
	<iso_3166_2_entry
		code="AR-B"	name="Buenos Aires" />
	<iso_3166_2_entry
		code="AR-K"	name="Catamarca" />
	<iso_3166_2_entry
		code="AR-X"	name="Cordoba" />
	<iso_3166_2_entry
		code="AR-W"	name="Corrientes" />
	<iso_3166_2_entry
		code="AR-H"	name="Chaco" />
	<iso_3166_2_entry
		code="AR-U"	name="Chubut" />
	<iso_3166_2_entry
		code="AR-E"	name="Entre Rios" />
	<iso_3166_2_entry
		code="AR-P"	name="Formosa" />
	<iso_3166_2_entry
		code="AR-Y"	name="Jujuy" />
	<iso_3166_2_entry
		code="AR-L"	name="La Pampa" />
	<iso_3166_2_entry
		code="AR-M"	name="Mendoza" />
	<iso_3166_2_entry
		code="AR-N"	name="Misiones" />
	<iso_3166_2_entry
		code="AR-Q"	name="Neuquen" />
	<iso_3166_2_entry
		code="AR-R"	name="Rio Negro" />
	<iso_3166_2_entry
		code="AR-A"	name="Salta" />
	<iso_3166_2_entry
		code="AR-J"	name="San Juan" />
	<iso_3166_2_entry
		code="AR-D"	name="San Luis" />
	<iso_3166_2_entry
		code="AR-Z"	name="Santa Cruz" />
	<iso_3166_2_entry
		code="AR-S"	name="Santa Fe" />
	<iso_3166_2_entry
		code="AR-G"	name="Santiago del Estero" />
	<iso_3166_2_entry
		code="AR-V"	name="Tierra del Fuego" />
	<iso_3166_2_entry
		code="AR-T"	name="Tucuman" />
</iso_3166_subset>
</iso_3166_country>
	<!-- Austria -->
<iso_3166_country code="AT">
<iso_3166_subset type="State">
	<iso_3166_2_entry
		code="AT-1"	name="Burgenland" />
	<iso_3166_2_entry
		code="AT-2"	name="Kärnten" />
	<iso_3166_2_entry
		code="AT-3"	name="Niederösterreich" />
	<iso_3166_2_entry
		code="AT-4"	name="Oberösterreich" />
	<iso_3166_2_entry
		code="AT-5"	name="Salzburg" />
	<iso_3166_2_entry
		code="AT-6"	name="Steiermark" />
	<iso_3166_2_entry
		code="AT-7"	name="Tirol" />
	<iso_3166_2_entry
		code="AT-8"	name="Vorarlberg" />
	<iso_3166_2_entry
		code="AT-9"	name="Wien" />
</iso_3166_subset>
</iso_3166_country>
	<!-- Australia -->
<iso_3166_country code="AU">
<iso_3166_subset type="State">
	<iso_3166_2_entry
		code="AU-NSW"	name="New South Wales" />
	<iso_3166_2_entry
		code="AU-QLD"	name="Queensland" />
	<iso_3166_2_entry
		code="AU-SA"	name="South Australia" />
	<iso_3166_2_entry
		code="AU-TAS"	name="Tasmania" />
	<iso_3166_2_entry
		code="AU-VIC"	name="Victoria" />
	<iso_3166_2_entry
		code="AU-WA"	name="Western Australia" />
</iso_3166_subset>
<iso_3166_subset type="Territory">
	<iso_3166_2_entry
		code="AU-ACT"	name="Australian Capital Territory" />
	<iso_3166_2_entry
		code="AU-NT"	name="Northern Territory" />
</iso_3166_subset>
</iso_3166_country>
	<!-- Azerbaijan -->
<iso_3166_country code="AZ">
<iso_3166_subset type="Autonomous republic">
	<iso_3166_2_entry
		code="AZ-NX"	name="Naxçıvan" />
</iso_3166_subset>
<iso_3166_subset type="Municipality">
	<iso_3166_2_entry
		code="AZ-BA"	name="Bakı" />
	<iso_3166_2_entry
		code="AZ-GA"	name="Gəncə" />
	<iso_3166_2_entry
		code="AZ-XA"	name="Xankəndi" />
	<iso_3166_2_entry
		code="AZ-LA"	name="Lənkəran" />
	<iso_3166_2_entry
		code="AZ-MI"	name="Mingəçevir" />
	<iso_3166_2_entry
		code="AZ-NA"	name="Naftalan" />
	<iso_3166_2_entry
		code="AZ-NV"	name="Naxçıvan"  parent="NX" />
	<iso_3166_2_entry
		code="AZ-SM"	name="Sumqayıt" />
	<iso_3166_2_entry
		code="AZ-SA"	name="Şəki" />
	<iso_3166_2_entry
		code="AZ-SR"	name="Şirvan" />
	<iso_3166_2_entry
		code="AZ-YE"	name="Yevlax" />
</iso_3166_subset>
<iso_3166_subset type="Rayon">
	<iso_3166_2_entry
		code="AZ-ABS"	name="Abşeron" />
	<iso_3166_2_entry
		code="AZ-AGC"	name="Ağcabədi" />
	<iso_3166_2_entry
		code="AZ-AGM"	name="Ağdam" />
	<iso_3166_2_entry
		code="AZ-AGS"	name="Ağdaş" />
	<iso_3166_2_entry
		code="AZ-AGA"	name="Ağstafa" />
	<iso_3166_2_entry
		code="AZ-AGU"	name="Ağsu" />
	<iso_3166_2_entry
		code="AZ-AST"	name="Astara" />
	<iso_3166_2_entry
		code="AZ-BAB"	name="Babək"	parent="NX" />
	<iso_3166_2_entry
		code="AZ-BAL"	name="Balakən" />
	<iso_3166_2_entry
		code="AZ-BEY"	name="Beyləqan" />
	<iso_3166_2_entry
		code="AZ-BAR"	name="Bərdə" />
	<iso_3166_2_entry
		code="AZ-BIL"	name="Biləsuvar" />
	<iso_3166_2_entry
		code="AZ-CAB"	name="Cəbrayıl" />
	<iso_3166_2_entry
		code="AZ-CAL"	name="Cəlilabab" />
	<iso_3166_2_entry
		code="AZ-CUL"	name="Culfa"	parent="NX" />
	<iso_3166_2_entry
		code="AZ-DAS"	name="Daşkəsən" />
	<iso_3166_2_entry
		code="AZ-FUZ"	name="Füzuli" />
	<iso_3166_2_entry
		code="AZ-GAD"	name="Gədəbəy" />
	<iso_3166_2_entry
		code="AZ-GOR"	name="Goranboy" />
	<iso_3166_2_entry
		code="AZ-GOY"	name="Göyçay" />
	<iso_3166_2_entry
		code="AZ-GYG"	name="Göygöl" />
	<iso_3166_2_entry
		code="AZ-HAC"	name="Hacıqabul" />
	<iso_3166_2_entry
		code="AZ-XAC"	name="Xaçmaz" />
	<iso_3166_2_entry
		code="AZ-XIZ"	name="Xızı" />
	<iso_3166_2_entry
		code="AZ-XCI"	name="Xocalı" />
	<iso_3166_2_entry
		code="AZ-XVD"	name="Xocavənd" />
	<iso_3166_2_entry
		code="AZ-IMI"	name="İmişli" />
	<iso_3166_2_entry
		code="AZ-ISM"	name="İsmayıllı" />
	<iso_3166_2_entry
		code="AZ-KAL"	name="Kəlbəcər" />
	<iso_3166_2_entry
		code="AZ-KAN"	name="Kǝngǝrli"  parent="NX" />
	<iso_3166_2_entry
		code="AZ-KUR"	name="Kürdəmir" />
	<iso_3166_2_entry
		code="AZ-QAX"	name="Qax" />
	<iso_3166_2_entry
		code="AZ-QAZ"	name="Qazax" />
	<iso_3166_2_entry
		code="AZ-QOB"	name="Qobustan" />
	<iso_3166_2_entry
		code="AZ-QBA"	name="Quba" />
	<iso_3166_2_entry
		code="AZ-QBI"	name="Qubadlı" />
	<iso_3166_2_entry
		code="AZ-QUS"	name="Qusar" />
	<iso_3166_2_entry
		code="AZ-LAC"	name="Laçın" />
	<iso_3166_2_entry
		code="AZ-LER"	name="Lerik" />
	<iso_3166_2_entry
		code="AZ-LAN"	name="Lənkəran" />
	<iso_3166_2_entry
		code="AZ-MAS"	name="Masallı" />
	<iso_3166_2_entry
		code="AZ-NEF"	name="Neftçala" />
	<iso_3166_2_entry
		code="AZ-OGU"	name="Oğuz" />
	<iso_3166_2_entry
		code="AZ-ORD"	name="Ordubad"	parent="NX" />
	<iso_3166_2_entry
		code="AZ-QAB"	name="Qəbələ" />
	<iso_3166_2_entry
		code="AZ-SAT"	name="Saatlı" />
	<iso_3166_2_entry
		code="AZ-SAB"	name="Sabirabad" />
	<iso_3166_2_entry
		code="AZ-SAL"	name="Salyan" />
	<iso_3166_2_entry
		code="AZ-SMX"	name="Samux" />
	<iso_3166_2_entry
		code="AZ-SAD"	name="Sədərək"	parent="NX" />
	<iso_3166_2_entry
		code="AZ-SIY"	name="Siyəzən" />
	<iso_3166_2_entry
		code="AZ-SBN"	name="Şabran" />
	<iso_3166_2_entry
		code="AZ-SAH"	name="Şahbuz"	parent="NX" />
	<iso_3166_2_entry
		code="AZ-SMI"	name="Şamaxı" />
	<iso_3166_2_entry
		code="AZ-SAK"	name="Şəki" />
	<iso_3166_2_entry
		code="AZ-SKR"	name="Şəmkir" />
	<iso_3166_2_entry
		code="AZ-SAR"	name="Şərur"	parent="NX" />
	<iso_3166_2_entry
		code="AZ-SUS"	name="Şuşa" />
	<iso_3166_2_entry
		code="AZ-TAR"	name="Tərtər" />
	<iso_3166_2_entry
		code="AZ-TOV"	name="Tovuz" />
	<iso_3166_2_entry
		code="AZ-UCA"	name="Ucar" />
	<iso_3166_2_entry
		code="AZ-YAR"	name="Yardımlı" />
	<iso_3166_2_entry
		code="AZ-YEV"	name="Yevlax" />
	<iso_3166_2_entry
		code="AZ-ZAQ"	name="Zaqatala" />
	<iso_3166_2_entry
		code="AZ-ZAN"	name="Zəngilan" />
	<iso_3166_2_entry
		code="AZ-ZAR"	name="Zərdab" />
</iso_3166_subset>
</iso_3166_country>
	<!-- Bosnia-Herzegovina -->
<iso_3166_country code="BA">
<iso_3166_subset type="Entity">
	<iso_3166_2_entry
		code="BA-BIH"	name="Federacija Bosne i Hercegovine" />
	<iso_3166_2_entry
		code="BA-SRP"	name="Republika Srpska" />
</iso_3166_subset>
<iso_3166_subset type="Canton">
	<iso_3166_2_entry
		code="BA-05"	name="Bosansko-podrinjski kanton" 	parent="BIH" />
	<iso_3166_2_entry
		code="BA-07"	name="Hercegovačko-neretvanski kanton"  	parent="BIH"/>
	<iso_3166_2_entry
		code="BA-10"	name="Kanton br. 10 (Livanjski kanton)"  	parent="BIH"/>
	<iso_3166_2_entry
		code="BA-09"	name="Kanton Sarajevo"  	parent="BIH"/>
	<iso_3166_2_entry
		code="BA-02"	name="Posavski kanton"  	parent="BIH"/>
	<iso_3166_2_entry
		code="BA-06"	name="Srednjobosanski kanton"  	parent="BIH"/>
	<iso_3166_2_entry
		code="BA-03"	name="Tuzlanski kanton"  	parent="BIH"/>
	<iso_3166_2_entry
		code="BA-01"	name="Unsko-sanski kanton"  	parent="BIH"/>
	<iso_3166_2_entry
		code="BA-08"	name="Zapadnohercegovački kanton"  	parent="BIH"/>
	<iso_3166_2_entry
		code="BA-04"	name="Zeničko-dobojski kanton"  	parent="BIH"/>
</iso_3166_subset>
<iso_3166_subset type="District">
	<iso_3166_2_entry
		code="BA-BRC"	name="Brčko distrikt" />
</iso_3166_subset>
</iso_3166_country>
	<!-- Barbados -->
<iso_3166_country code="BB">
<iso_3166_subset type="Parish">
	<iso_3166_2_entry
		code="BB-01"	name="Christ Church" />
	<iso_3166_2_entry
		code="BB-02"	name="Saint Andrew" />
	<iso_3166_2_entry
		code="BB-03"	name="Saint George" />
	<iso_3166_2_entry
		code="BB-04"	name="Saint James" />
	<iso_3166_2_entry
		code="BB-05"	name="Saint John" />
	<iso_3166_2_entry
		code="BB-06"	name="Saint Joseph" />
	<iso_3166_2_entry
		code="BB-07"	name="Saint Lucy" />
	<iso_3166_2_entry
		code="BB-08"	name="Saint Michael" />
	<iso_3166_2_entry
		code="BB-09"	name="Saint Peter" />
	<iso_3166_2_entry
		code="BB-10"	name="Saint Philip" />
	<iso_3166_2_entry
		code="BB-11"	name="Saint Thomas" />
</iso_3166_subset>
</iso_3166_country>
	<!-- Bangladesh -->
<iso_3166_country code="BD">
<iso_3166_subset type="Division">
	<iso_3166_2_entry
		code="BD-A"	name="Barisal" />
	<iso_3166_2_entry
		code="BD-B"	name="Chittagong" />
	<iso_3166_2_entry
		code="BD-C"	name="Dhaka" />
	<iso_3166_2_entry
		code="BD-D"	name="Khulna" />
	<iso_3166_2_entry
		code="BD-E"	name="Rajshahi" />
	<iso_3166_2_entry
		code="BD-F"	name="Rangpur" />
	<iso_3166_2_entry
		code="BD-G"	name="Sylhet" />
</iso_3166_subset>
<iso_3166_subset type="District">
	<iso_3166_2_entry
		code="BD-05"	name="Bagerhat"	parent="D" />
	<iso_3166_2_entry
		code="BD-01"	name="Bandarban"	parent="B" />
	<iso_3166_2_entry
		code="BD-02"	name="Barguna"	parent="A" />
	<iso_3166_2_entry
		code="BD-06"	name="Barisal"	parent="A" />
	<iso_3166_2_entry
		code="BD-07"	name="Bhola"	parent="A" />
	<iso_3166_2_entry
		code="BD-03"	name="Bogra"	parent="E" />
	<iso_3166_2_entry
		code="BD-04"	name="Brahmanbaria"	parent="B" />
	<iso_3166_2_entry
		code="BD-09"	name="Chandpur"	parent="B" />
	<iso_3166_2_entry
		code="BD-10"	name="Chittagong"	parent="B" />
	<iso_3166_2_entry
		code="BD-12"	name="Chuadanga"	parent="D" />
	<iso_3166_2_entry
		code="BD-08"	name="Comilla"	parent="B" />
	<iso_3166_2_entry
		code="BD-11"	name="Cox's Bazar"	parent="B" />
	<iso_3166_2_entry
		code="BD-13"	name="Dhaka"	parent="C" />
	<iso_3166_2_entry
		code="BD-14"	name="Dinajpur"	parent="F" />
	<iso_3166_2_entry
		code="BD-15"	name="Faridpur"	parent="C" />
	<iso_3166_2_entry
		code="BD-16"	name="Feni"	parent="B" />
	<iso_3166_2_entry
		code="BD-19"	name="Gaibandha"	parent="F" />
	<iso_3166_2_entry
		code="BD-18"	name="Gazipur"	parent="C" />
	<iso_3166_2_entry
		code="BD-17"	name="Gopalganj"	parent="C" />
	<iso_3166_2_entry
		code="BD-20"	name="Habiganj"	parent="G" />
	<iso_3166_2_entry
		code="BD-24"	name="Jaipurhat"	parent="E" />
	<iso_3166_2_entry
		code="BD-21"	name="Jamalpur"	parent="C" />
	<iso_3166_2_entry
		code="BD-22"	name="Jessore"	parent="D" />
	<iso_3166_2_entry
		code="BD-25"	name="Jhalakati"	parent="A" />
	<iso_3166_2_entry
		code="BD-23"	name="Jhenaidah"	parent="D" />
	<iso_3166_2_entry
		code="BD-29"	name="Khagrachari"	parent="B" />
	<iso_3166_2_entry
		code="BD-27"	name="Khulna"	parent="D" />
	<iso_3166_2_entry
		code="BD-26"	name="Kishorganj"	parent="C" />
	<iso_3166_2_entry
		code="BD-28"	name="Kurigram"	parent="F" />
	<iso_3166_2_entry
		code="BD-30"	name="Kushtia"	parent="D" />
	<iso_3166_2_entry
		code="BD-31"	name="Lakshmipur"	parent="B" />
	<iso_3166_2_entry
		code="BD-32"	name="Lalmonirhat"	parent="F" />
	<iso_3166_2_entry
		code="BD-36"	name="Madaripur"	parent="C" />
	<iso_3166_2_entry
		code="BD-37"	name="Magura"	parent="D" />
	<iso_3166_2_entry
		code="BD-33"	name="Manikganj"	parent="C" />
	<iso_3166_2_entry
		code="BD-39"	name="Meherpur"	parent="D" />
	<iso_3166_2_entry
		code="BD-38"	name="Moulvibazar"	parent="G" />
	<iso_3166_2_entry
		code="BD-35"	name="Munshiganj"	parent="C" />
	<iso_3166_2_entry
		code="BD-34"	name="Mymensingh"	parent="C" />
	<iso_3166_2_entry
		code="BD-48"	name="Naogaon"	parent="E" />
	<iso_3166_2_entry
		code="BD-43"	name="Narail"	parent="D" />
	<iso_3166_2_entry
		code="BD-40"	name="Narayanganj"	parent="C" />
	<iso_3166_2_entry
		code="BD-42"	name="Narsingdi"	parent="C" />
	<iso_3166_2_entry
		code="BD-44"	name="Natore"	parent="E" />
	<iso_3166_2_entry
		code="BD-45"	name="Nawabganj"	parent="E" />
	<iso_3166_2_entry
		code="BD-41"	name="Netrakona"	parent="C" />
	<iso_3166_2_entry
		code="BD-46"	name="Nilphamari"	parent="F" />
	<iso_3166_2_entry
		code="BD-47"	name="Noakhali"	parent="B" />
	<iso_3166_2_entry
		code="BD-49"	name="Pabna"	parent="E" />
	<iso_3166_2_entry
		code="BD-52"	name="Panchagarh"	parent="F" />
	<iso_3166_2_entry
		code="BD-51"	name="Patuakhali"	parent="A" />
	<iso_3166_2_entry
		code="BD-50"	name="Pirojpur"	parent="A" />
	<iso_3166_2_entry
		code="BD-53"	name="Rajbari"	parent="C" />
	<iso_3166_2_entry
		code="BD-54"	name="Rajshahi"	parent="E" />
	<iso_3166_2_entry
		code="BD-56"	name="Rangamati"	parent="B" />
	<iso_3166_2_entry
		code="BD-55"	name="Rangpur"	parent="F" />
	<iso_3166_2_entry
		code="BD-58"	name="Satkhira"	parent="D" />
	<iso_3166_2_entry
		code="BD-62"	name="Shariatpur"	parent="C" />
	<iso_3166_2_entry
		code="BD-57"	name="Sherpur"	parent="C" />
	<iso_3166_2_entry
		code="BD-59"	name="Sirajganj"	parent="E" />
	<iso_3166_2_entry
		code="BD-61"	name="Sunamganj"	parent="G" />
	<iso_3166_2_entry
		code="BD-60"	name="Sylhet"	parent="G" />
	<iso_3166_2_entry
		code="BD-63"	name="Tangail"	parent="C" />
	<iso_3166_2_entry
		code="BD-64"	name="Thakurgaon"	parent="F" />
</iso_3166_subset>
</iso_3166_country>
	<!-- Belgium -->
<iso_3166_country code="BE">
<iso_3166_subset type="Region">
	<iso_3166_2_entry
		code="BE-BRU"	name="Bruxelles-Capitale, Région de;Brussels Hoofdstedelijk Gewest" />
	<iso_3166_2_entry
		code="BE-VLG"	name="Vlaams Gewest" />
	<iso_3166_2_entry
		code="BE-WAL"	name="wallonne, Région" />
</iso_3166_subset>
<iso_3166_subset type="Province">
	<iso_3166_2_entry
		code="BE-VAN"	name="Antwerpen" parent="VLG"/>
	<iso_3166_2_entry
		code="BE-WBR"	name="Brabant wallon" parent="WAL"/>
	<iso_3166_2_entry
		code="BE-WHT"	name="Hainaut"  parent="WAL"/>
	<iso_3166_2_entry
		code="BE-WLG"	name="Liège"  parent="WAL"/>
	<iso_3166_2_entry
		code="BE-VLI"	name="Limburg"  parent="VLG"/>
	<iso_3166_2_entry
		code="BE-WLX"	name="Luxembourg"  parent="WAL"/>
	<iso_3166_2_entry
		code="BE-WNA"	name="Namur"  parent="WAL"/>
	<iso_3166_2_entry
		code="BE-VOV"	name="Oost-Vlaanderen"  parent="VLG"/>
	<iso_3166_2_entry
		code="BE-VBR"	name="Vlaams-Brabant"  parent="VLG"/>
	<iso_3166_2_entry
		code="BE-VWV"	name="West-Vlaanderen"  parent="VLG"/>
</iso_3166_subset>
</iso_3166_country>
	<!-- Burkina-Faso -->
<iso_3166_country code="BF">
<iso_3166_subset type="Region">
	<iso_3166_2_entry
		code="BF-01"	name="Boucle du Mouhoun" />
	<iso_3166_2_entry
		code="BF-02"	name="Cascades" />
	<iso_3166_2_entry
		code="BF-03"	name="Centre" />
	<iso_3166_2_entry
		code="BF-04"	name="Centre-Est" />
	<iso_3166_2_entry
		code="BF-05"	name="Centre-Nord" />
	<iso_3166_2_entry
		code="BF-06"	name="Centre-Ouest" />
	<iso_3166_2_entry
		code="BF-07"	name="Centre-Sud" />
	<iso_3166_2_entry
		code="BF-08"	name="Est" />
	<iso_3166_2_entry
		code="BF-09"	name="Hauts-Bassins" />
	<iso_3166_2_entry
		code="BF-10"	name="Nord" />
	<iso_3166_2_entry
		code="BF-11"	name="Plateau-Central" />
	<iso_3166_2_entry
		code="BF-12"	name="Sahel" />
	<iso_3166_2_entry
		code="BF-13"	name="Sud-Ouest" />
</iso_3166_subset>
<iso_3166_subset type="Province">
	<iso_3166_2_entry
		code="BF-BAL"	name="Balé"	parent="01" />
	<iso_3166_2_entry
		code="BF-BAM"	name="Bam"	parent="05" />
	<iso_3166_2_entry
		code="BF-BAN"	name="Banwa"	parent="01" />
	<iso_3166_2_entry
		code="BF-BAZ"	name="Bazèga"	parent="07" />
	<iso_3166_2_entry
		code="BF-BGR"	name="Bougouriba"	parent="13" />
	<iso_3166_2_entry
		code="BF-BLG"	name="Boulgou"	parent="04" />
	<iso_3166_2_entry
		code="BF-BLK"	name="Boulkiemdé"	parent="06" />
	<iso_3166_2_entry
		code="BF-COM"	name="Comoé"	parent="02" />
	<iso_3166_2_entry
		code="BF-GAN"	name="Ganzourgou"	parent="11" />
	<iso_3166_2_entry
		code="BF-GNA"	name="Gnagna"	parent="08" />
	<iso_3166_2_entry
		code="BF-GOU"	name="Gourma"	parent="08" />
	<iso_3166_2_entry
		code="BF-HOU"	name="Houet"	parent="09" />
	<iso_3166_2_entry
		code="BF-IOB"	name="Ioba"	parent="13" />
	<iso_3166_2_entry
		code="BF-KAD"	name="Kadiogo"	parent="03" />
	<iso_3166_2_entry
		code="BF-KEN"	name="Kénédougou"	parent="09" />
	<iso_3166_2_entry
		code="BF-KMD"	name="Komondjari"	parent="08" />
	<iso_3166_2_entry
		code="BF-KMP"	name="Kompienga"	parent="08" />
	<iso_3166_2_entry
		code="BF-KOS"	name="Kossi"	parent="01" />
	<iso_3166_2_entry
		code="BF-KOP"	name="Koulpélogo"	parent="04" />
	<iso_3166_2_entry
		code="BF-KOT"	name="Kouritenga"	parent="04" />
	<iso_3166_2_entry
		code="BF-KOW"	name="Kourwéogo"	parent="11" />
	<iso_3166_2_entry
		code="BF-LER"	name="Léraba"	parent="02" />
	<iso_3166_2_entry
		code="BF-LOR"	name="Loroum"	parent="10" />
	<iso_3166_2_entry
		code="BF-MOU"	name="Mouhoun"	parent="01" />
	<iso_3166_2_entry
		code="BF-NAO"	name="Naouri"	parent="07" />
	<iso_3166_2_entry
		code="BF-NAM"	name="Namentenga"	parent="05" />
	<iso_3166_2_entry
		code="BF-NAY"	name="Nayala"	parent="01" />
	<iso_3166_2_entry
		code="BF-NOU"	name="Noumbiel"	parent="13" />
	<iso_3166_2_entry
		code="BF-OUB"	name="Oubritenga"	parent="11" />
	<iso_3166_2_entry
		code="BF-OUD"	name="Oudalan"	parent="12" />
	<iso_3166_2_entry
		code="BF-PAS"	name="Passoré"	parent="10" />
	<iso_3166_2_entry
		code="BF-PON"	name="Poni"	parent="13" />
	<iso_3166_2_entry
		code="BF-SNG"	name="Sanguié"	parent="06" />
	<iso_3166_2_entry
		code="BF-SMT"	name="Sanmatenga"	parent="05" />
	<iso_3166_2_entry
		code="BF-SEN"	name="Séno"	parent="12" />
	<iso_3166_2_entry
		code="BF-SIS"	name="Sissili"	parent="06" />
	<iso_3166_2_entry
		code="BF-SOM"	name="Soum"	parent="12" />
	<iso_3166_2_entry
		code="BF-SOR"	name="Sourou"	parent="01" />
	<iso_3166_2_entry
		code="BF-TAP"	name="Tapoa"	parent="08" />
	<iso_3166_2_entry
		code="BF-TUI"	name="Tui"	parent="09" />
	<iso_3166_2_entry
		code="BF-YAG"	name="Yagha"	parent="12" />
	<iso_3166_2_entry
		code="BF-YAT"	name="Yatenga"	parent="10" />
	<iso_3166_2_entry
		code="BF-ZIR"	name="Ziro"	parent="06" />
	<iso_3166_2_entry
		code="BF-ZON"	name="Zondoma"	parent="10" />
	<iso_3166_2_entry
		code="BF-ZOU"	name="Zoundwéogo"	parent="07" />
</iso_3166_subset>
</iso_3166_country>
	<!-- Bulgaria -->
<iso_3166_country code="BG">
<iso_3166_subset type="Region">
	<iso_3166_2_entry
		code="BG-01"	name="Blagoevgrad" />
	<iso_3166_2_entry
		code="BG-02"	name="Burgas" />
	<iso_3166_2_entry
		code="BG-08"	name="Dobrich" />
	<iso_3166_2_entry
		code="BG-07"	name="Gabrovo" />
	<iso_3166_2_entry
		code="BG-26"	name="Haskovo" />
	<iso_3166_2_entry
		code="BG-09"	name="Kardzhali" />
	<iso_3166_2_entry
		code="BG-10"	name="Kyustendil" />
	<iso_3166_2_entry
		code="BG-11"	name="Lovech" />
	<iso_3166_2_entry
		code="BG-12"	name="Montana" />
	<iso_3166_2_entry
		code="BG-13"	name="Pazardzhik" />
	<iso_3166_2_entry
		code="BG-14"	name="Pernik" />
	<iso_3166_2_entry
		code="BG-15"	name="Pleven" />
	<iso_3166_2_entry
		code="BG-16"	name="Plovdiv" />
	<iso_3166_2_entry